version: '3.9'

services:
  do_api_volume_snapshot:
    build: .
    # Create a Docker volume in /app on the Docker container
    # to house the Python script outputs and mounts the volume
    # in the current working directory on the Docker host
    volumes:
      - .:/app
    # Limit logs to 3 files with a max size of 100Mb each
    logging:
      driver: 'json-file'
      options:
        max-size: '20'
        max-file: '5'
    # Cron in foreground as the entry point for the container
    command: cron -f